[package]
name = "spec"
edition = "2024.beta"

[dependencies]
MoveStdlib = { local = "../../../../crates/sui-framework/packages/move-stdlib", override = true }
Sui = { local = "../../../../crates/sui-framework/packages/sui-framework", override = true }
Bridge = { local = "../../../../crates/sui-framework/packages/bridge" }
cvlm = { git = "https://github.com/Certora/cvl-move-proto.git", subdir = "cvlm", rev = "eric/asserts" }
certora_sui_summaries = { git = "https://github.com/Certora/cvl-move-proto.git", subdir = "certora_sui_summaries",  rev = "eric/asserts" }
# cvlm = { local = "/home/eric/src/cvl-move-proto/cvlm" }
# certora_sui_summaries = { local = "/home/eric/src/cvl-move-proto/certora_sui_summaries" }

[addresses]
spec = "0x0"
