[package]
name = "Bridge"
version = "0.0.1"
published-at = "0xb"
edition = "2024.beta"

[dependencies]
MoveStdlib = { local = "../move-stdlib", override = true }
Sui = { local = "../sui-framework", override = true }
SuiSystem = { local = "../sui-system", override = true }

[addresses]
bridge = "0xb"
cvlm = "0x436572746f7261"

[dev-dependencies]
# cvlm = { git = "https://github.com/Certora/cvl-move-proto.git", subdir = "cvlm", rev = "main" }
# certora_sui_summaries = { git = "https://github.com/Certora/cvl-move-proto.git", subdir = "certora_sui_summaries",  rev = "main" }
cvlm = { local = "/home/eric/src/cvl-move-proto/cvlm" }
certora_sui_summaries = { local = "/home/eric/src/cvl-move-proto/certora_sui_summaries" }

